<?php

namespace AppBundle\DocumentRepository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AppInstallsRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class AppInstallsRepository extends DocumentRepository
{
}
