<?php

namespace AppBundle\DocumentRepository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AppVersionsRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class AppVersionsRepository extends DocumentRepository
{
}
