<?php

namespace AppBundle\DocumentRepository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DeveloperManagersRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class DeveloperManagersRepository extends DocumentRepository
{
}
