<?php

namespace AppBundle\EntityRepository;

/**
 * AppsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppsRepository extends \Doctrine\ORM\EntityRepository
{
}
