<?php

namespace AppBundle\EntityRepository;

/**
 * DevelopersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevelopersRepository extends \Doctrine\ORM\EntityRepository
{
}
